MedicReach-main/MedicReach/Areas/Admin/Models/Physicians/AllPhysiciansAdminQueryModel.cs
using MedicReach.Models.Physicians.Enums;
using MedicReach.Services.Physicians.Models;
using System.Collections.Generic;

namespace MedicReach.Areas.Admin.Models.Physicians
{
    public class AllPhysiciansAdminQueryModel
    {
        public const int PhysiciansPerPage = 2;

        public int CurrentPage { get; init; } = 1;

        public bool Approved { get; set; }

        public PhysicianSorting Sorting { get; init; }

        public IEnumerable<PhysicianServiceModel> Physicians { get; set; }

        public int TotalPhysicians { get; set; }
    }
}

MedicReach-main/MedicReach/Models/Physicians/AllPhysiciansQueryModel.cs
using MedicReach.Models.Physicians.Enums;
using MedicReach.Services.Physicians.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MedicReach.Models.Physicians
{
    public class AllPhysiciansQueryModel
    {
        public const int PhysiciansPerPage = 3;

        public int CurrentPage { get; init; } = 1;

        public string Speciality { get; init; }

        [Display(Name = "Find by Speciality")]
        public IEnumerable<string> Specialities { get; set; }

        [Display(Name = "Find by Medical Center")]
        public IEnumerable<string> MedicalCenters { get; set; }

        public string MedicalCenter { get; init; }

        public bool Approved { get; set; } = true;

        [Display(Name = "Find by Name")]
        public string SearchTerm { get; init; }

        [Display(Name = "Sort by")]
        public PhysicianSorting Sorting { get; init; }

        public IEnumerable<PhysicianServiceModel> Physicians { get; set; }

        public int TotalPhysicians { get; set; }
    }
}

MedicReach-main/MedicReach/Models/Physicians/Enums/PhysicianSorting.cs
namespace MedicReach.Models.Physicians.Enums
{
    public enum PhysicianSorting
    {
        DateCreated = 0,
        ExaminationPriceAsc = 1,
        ExaminationPriceDesc = 2,
        NameAsc = 3,
        NameDesc = 4,
        Unapproved  = 5,
        Approved = 6
    }
}

MedicReach-main/MedicReach/Models/Physicians/PhysicianFormModel.cs
using MedicReach.Services.Physicians.Models;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using static MedicReach.Data.DataConstants.Physician;

namespace MedicReach.Models.Physicians
{
    public class PhysicianFormModel
    {
        [Required]
        [StringLength(NameMaxLength, MinimumLength = NameMinLength)]
        [Display(Name = "Full Name")]
        public string FullName { get; init; }

        [Required]
        public string Gender { get; init; }

        [Required]
        [Display(Name = "Medical Center")]
        public string MedicalCenterId { get; init; }

        [Required]
        [Display(Name = "Medical Center Joining Code")]
        public string JoiningCode { get; set; }

        [Range(ExaminationPriceMinValue, ExaminationPriceMaxValue)]
        [Display(Name = "Examination Price €")]
        public int ExaminationPrice { get; set; }

        [Url]
        [Display(Name = "Image")]
        public string ImageUrl { get; set; }

        [Display(Name = "Speciality")]
        public int SpecialityId { get; set; }

        public IEnumerable<PhysicianMedicalCentersServiceModel> MedicalCenters { get; set; }

        public IEnumerable<PhysicianSpecialityServiceModel> Specialities { get; set; }

        [Display(Name = "Works with children")]
        public bool IsWorkingWithChildren { get; set; }

        [Required]
        [StringLength(PermissionPracticeMaxLength, MinimumLength = PermissionPracticeMinLength)]
        [Display(Name = "Practice Permission Number")]
        public string PracticePermissionNumber { get; set; }

        [Display(Name = "Approved")]
        public bool IsApproved { get; set; }
    }
}

MedicReach-main/MedicReach/Areas/Admin/Controllers/MedicalCentersController.cs
using MedicReach.Areas.Admin.Models.MedicalCenters;
using MedicReach.Models.MedicalCenters.Enums;
using MedicReach.Services.MedicalCenters;
using Microsoft.AspNetCore.Mvc;

namespace MedicReach.Areas.Admin.Controllers
{
    public class MedicalCentersController : AdminController
    {
        private readonly IMedicalCenterService medicalCenters;

        public MedicalCentersController(IMedicalCenterService medicalCenters) 
            => this.medicalCenters = medicalCenters;

        public IActionResult All(AllMedicalCentersAdminQueryModel query)
        {
            var queryResult = this.medicalCenters
                    .All(
                        null,
                        null,
                        query.SearchTerm,
                        MedicalCentersSorting.DateCreated,
                        query.CurrentPage,
                        AllMedicalCentersAdminQueryModel.MedicalCentersPerPage
                        );

            query.MedicalCenters = queryResult.MedicalCenters;
            query.TotalMedicalCenters = queryResult.TotalMedicalCenters;

            return View(query);
        }
    }
}

MedicReach-main/MedicReach/Areas/Admin/Controllers/PhysiciansController.cs
using MedicReach.Areas.Admin.Models.Physicians;
using MedicReach.Services.Physicians;
using Microsoft.AspNetCore.Mvc;


namespace MedicReach.Areas.Admin.Controllers
{
    public class PhysiciansController : AdminController
    {
        private readonly IPhysicianService physicians;

        public PhysiciansController(IPhysicianService physicians) 
            => this.physicians = physicians;

        public IActionResult All(AllPhysiciansAdminQueryModel query)
        {
            var queryResult = this.physicians
                .All(
                    null,
                    null,
                    null,
                    query.Sorting,
                    query.CurrentPage,
                    AllPhysiciansAdminQueryModel.PhysiciansPerPage,
                    approved: false
                    );

            query.Physicians = queryResult.Physicians;
            query.TotalPhysicians = queryResult.TotalPhysicians;

            return View(query);
        }

        public IActionResult Approve(string physicianId)
        {
            this.physicians.ChangeApprovalStatus(physicianId);

            return RedirectToAction(nameof(All));
        }
    }
}

MedicReach-main/MedicReach/Controllers/PhysiciansController.cs
using AutoMapper;
using MedicReach.Infrastructure;
using MedicReach.Models.Physicians;
using MedicReach.Services.MedicalCenters;
using MedicReach.Services.Physicians;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using static MedicReach.WebConstants;
using static MedicReach.Areas.Admin.AdminConstants;

namespace MedicReach.Controllers
{
    public class PhysiciansController : Controller
    {
        private readonly IPhysicianService physicians;
        private readonly IMedicalCenterService medicalCenters;
        private readonly IMapper mapper;
        private readonly SignInManager<IdentityUser> signInManager;

        public PhysiciansController(
            IPhysicianService physicians,
            IMedicalCenterService medicalCenters,
            IMapper mapper,
            SignInManager<IdentityUser> signInManager)
        {
            this.physicians = physicians;
            this.medicalCenters = medicalCenters;
            this.mapper = mapper;
            this.signInManager = signInManager;
        }

        public IActionResult All([FromQuery] AllPhysiciansQueryModel query)
        {
            var queryResult = this.physicians.All(
                query.Speciality,
                query.MedicalCenter,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllPhysiciansQueryModel.PhysiciansPerPage,
                query.Approved);

            var physicianSpecialities = this.physicians.AllSpecialities();
            var medicalCenters = this.physicians.AllMedicalCenters();

            query.MedicalCenters = medicalCenters;
            query.Specialities = physicianSpecialities;
            query.Physicians = queryResult.Physicians;
            query.TotalPhysicians = queryResult.TotalPhysicians;

            return View(query);
        }

        [Authorize]
        public IActionResult Become()
        {
            var userIsPhysicians = this.physicians.IsPhysician(this.User.GetId());

            if (userIsPhysicians)
            {
                return RedirectToAction(nameof(Mine));
            }

            return View(new PhysicianFormModel
            {
                MedicalCenters = this.physicians.GetMedicalCenters(),
                Specialities = this.physicians.GetSpecialities()
            });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Become(PhysicianFormModel physicianModel)
        {
            if (!this.physicians.MedicalCenterExists(physicianModel.MedicalCenterId))
            {
                this.ModelState.AddModelError(nameof(physicianModel.MedicalCenterId), "Cơ sở không tồn tại.");
            }

            if (!this.physicians.SpecialityExists(physicianModel.SpecialityId))
            {
                this.ModelState.AddModelError(nameof(physicianModel.SpecialityId), "Chuyên môn không tồn tại.");
            }

            if (!this.medicalCenters.IsJoiningCodeCorrect(physicianModel.JoiningCode, physicianModel.MedicalCenterId))
            {
                this.ModelState.AddModelError(nameof(physicianModel.JoiningCode), "Joining code is incorrect.");
            }

            if (this.physicians.PracticePermissionNumberExists(physicianModel.PracticePermissionNumber))
            {
                this.ModelState.AddModelError(nameof(physicianModel.PracticePermissionNumber), "Practice permission number already exists.");
            }

            if (!this.ModelState.IsValid)
            {
                physicianModel.MedicalCenters = this.physicians.GetMedicalCenters();
                physicianModel.Specialities = this.physicians.GetSpecialities();

                return View(physicianModel);
            }

            this.physicians.Create(
                physicianModel.FullName,
                physicianModel.Gender,
                physicianModel.ExaminationPrice,
                physicianModel.MedicalCenterId,
                physicianModel.ImageUrl,
                physicianModel.SpecialityId,
                physicianModel.IsWorkingWithChildren,
                physicianModel.PracticePermissionNumber,
                physicianModel.IsApproved,
                this.User.GetId());

            Task.Run(async () =>
                {
                    await this.signInManager.SignOutAsync();
                })
                .GetAwaiter()
                .GetResult();

            this.TempData[GlobalSuccessMessageKey] = BecomePhysicianSuccessMessage;

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = PhysicianRoleName + "," + AdministratorRoleName)]
        public IActionResult Edit(string physicianId)
        {
            var physician = this.physicians.Details(physicianId);

            var physicianForm = this.mapper.Map<PhysicianFormModel>(physician);

            physicianForm.MedicalCenters = this.physicians.GetMedicalCenters();
            physicianForm.Specialities = this.physicians.GetSpecialities();
            physicianForm.JoiningCode = this.medicalCenters.GetJoiningCode(physicianForm.MedicalCenterId);

            return View(physicianForm);
        }

        [Authorize(Roles = PhysicianRoleName + "," + AdministratorRoleName)]
        [HttpPost]
        public IActionResult Edit(string physicianId, PhysicianFormModel physicianModel)
        {
            if (!this.medicalCenters.IsJoiningCodeCorrect(physicianModel.JoiningCode, physicianModel.MedicalCenterId))
            {
                this.ModelState.AddModelError(nameof(physicianModel.JoiningCode), "Joining code is incorrect.");
            }

            if (!physicianModel.PracticePermissionNumber.Equals(this.physicians.GetPracticePermissionByPhysiciandId(physicianId)))
            {
                if (this.physicians.PracticePermissionNumberExists(physicianModel.PracticePermissionNumber))
                {
                    this.ModelState.AddModelError(nameof(physicianModel.PracticePermissionNumber), "Practice permission number already exists.");
                }
            }

            if (!this.ModelState.IsValid)
            {
                physicianModel.MedicalCenters = this.physicians.GetMedicalCenters();
                physicianModel.Specialities = this.physicians.GetSpecialities();

                return View(physicianModel);
            }

            this.physicians.Edit(
                physicianId,
                physicianModel.FullName,
                physicianModel.Gender,
                physicianModel.ExaminationPrice,
                physicianModel.MedicalCenterId,
                physicianModel.ImageUrl,
                physicianModel.SpecialityId,
                physicianModel.IsWorkingWithChildren,
                physicianModel.PracticePermissionNumber,
                physicianModel.IsApproved,
                this.User.GetId());

            this.TempData[GlobalSuccessMessageKey] = this.User.IsAdmin() ? AdminEditPhysicianSuccessMessage : EditPhysicianSuccessMessage;

            return RedirectToAction(nameof(Details), new { physicianId });
        }

        public IActionResult Details(string physicianId)
        {
            var physician = this.physicians.Details(physicianId);

            return View(physician);
        }

        [Authorize(Roles = PhysicianRoleName)]
        public IActionResult Mine()
        {
            var physicianId = this.physicians.GetPhysicianId(this.User.GetId());

            if (string.IsNullOrEmpty(physicianId))
            {
                return RedirectToAction(nameof(Become));
            }

            return RedirectToAction(nameof(Edit), new { physicianId });
        }
    }
}

MedicReach-main/MedicReach/Controllers/ReviewsController.cs
using MedicReach.Models.Reviews;
using MedicReach.Services.Appointments;
using MedicReach.Services.Physicians;
using MedicReach.Services.Reviews;
using MedicReach.Services.Reviews.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static MedicReach.WebConstants;

namespace MedicReach.Controllers
{
    public class ReviewsController : Controller
    {
        private readonly IReviewService reviews;
        private readonly IAppointmentService appointments;
        private readonly IPhysicianService physicians;

        public ReviewsController(
            IReviewService reviews, 
            IAppointmentService appointments, 
            IPhysicianService physicians)
        {
            this.reviews = reviews;
            this.appointments = appointments;
            this.physicians = physicians;
        }

        [Authorize(Roles = PatientRoleName)]
        public IActionResult Write(string appointmentId)
        {
            var appointment = this.appointments.GetAppointment(appointmentId);

            return View(new ReviewFormModel
            {
                PatientId = appointment.PatientId,
                PhysicianId = appointment.PhysicianId,
                AppointmentId = appointment.Id
            });
        }

        [Authorize(Roles = PatientRoleName)]
        [HttpPost]
        public IActionResult Write(ReviewFormModel review)
        {
            this.reviews.Create(
                review.PatientId,
                review.PhysicianId,
                review.AppointmentId,
                review.Rating,
                review.Comment);

            this.TempData[GlobalSuccessMessageKey] = WriteReviewSuccessMessage;

            return RedirectToAction("Mine", "Appointments");
        }

        public IActionResult All(string physicianId, AllReviewsQueryModel query)
        {
            var queryResult = this.reviews.AllReviews(
                physicianId,
                query.Sorting,
                query.CurrentPage,
                AllReviewsQueryModel.ReviewsPerPage);

            query.TotalReviews = queryResult.TotalReviews;
            query.Reviews = queryResult.Reviews;

            return View(query);
        }
    }
}

MedicReach-main/MedicReach/Views/Physicians/All.cshtml
@model AllPhysiciansQueryModel

@{ ViewData["Title"] = "Bác sĩ"; 
}
<form method="get">
    <div class="row">
        <div class="form-group col-md-3">
            <label asp-for="SearchTerm">Tìm theo tên </label>
            <input asp-for="SearchTerm" class="form-control" placeholder="John Johnson, ...">
        </div>
        <div class="form-group col-md-3">
            <div class="form-group">
                <label asp-for="Speciality">Chuyên môn</label>
                <select asp-for="Speciality" class="form-control">
                    <option value="" selected>Tất cả</option>
                    @foreach (var speciality in Model.Specialities)
                    {
                        <option value="@speciality">@speciality</option>
                    }
                </select>
            </div>
        </div>
        <div class="form-group col-md-3">
            <div class="form-group">
                <label asp-for="MedicalCenter">Cơ sở </label>
                <select asp-for="MedicalCenter" class="form-control">
                    <option value="" selected>Tất cả</option>
                    @foreach (var medicalCenter in Model.MedicalCenters)
                    {
        <option value="@medicalCenter">@medicalCenter</option>
}
                </select>
            </div>
        </div>
        @if (User.IsAdmin())
        {
            <div class="form-group col-md-3">
                <label asp-for="Approved"></label>
                <select asp-for="Approved" class="form-control">
                    <option value="true">Đã được phê duyệt</option>
                    <option value="false">Chưa được phê duyệt</option>
                </select>
            </div>
        }
        @if (!User.IsAdmin())
        {
            <div class="form-group col-md-3">
                <label asp-for="Sorting">Tìm kiếm theo</label>
                <select asp-for="Sorting" class="form-control">
                    <option value="0" selected>Ngày tham gia</option>

                    <option value="3">Tên (tăng dần)</option>
                    <option value="4">Tên (Giảm dần)</option>
                </select>
            </div>
        }
    </div>
    <div class="row">
        <div class="form-group col-md-3">
            <input type="submit" class="btn btn-primary" value="Tìm kiếm">
        </div>
    </div>
</form>

<partial name="_PhysiciansPartial" model="@Model.Physicians" />

@{ var previousPage = Model.CurrentPage - 1;

                if (previousPage < 1)
                {
                    previousPage = 1;
                }

                var maxPage = Math.Ceiling((double)Model.TotalPhysicians / AllPhysiciansQueryModel.PhysiciansPerPage); }

@if (!Model.Physicians.Any())
{
    <h2 class="text-center">Không có bác sĩ nào được tìm thấy !</h2>
}

<div class="row">
    <div class="col-md-6">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Physicians"
           asp-action="All"
           asp-route-currentPage="@previousPage"
           asp-route-speciality="@Model.Speciality"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@Model.Sorting"><<</a>
    </div>
    <div class="col-md-6">
        <a class="btn btn-primary float-right @(Model.CurrentPage == maxPage ? "disabled" : string.Empty)"
           asp-controller="Physicians"
           asp-action="All"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-speciality="@Model.Speciality"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-sorting="@Model.Sorting">>></a>
    </div>
</div>

MedicReach-main/MedicReach/Views/Physicians/Become.cshtml
@model PhysicianFormModel

@{
    ViewData["Title"] = "Become physician";
}

<partial name="_PhysicianFormPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MedicReach-main/MedicReach/Views/Physicians/Details.cshtml
@model PhysicianServiceModel

@{ ViewData["Title"] = "Thông tin Bác Sĩ"; }

<div class="jumbotron offset-lg-2 col-lg-8 col-sm-12">
    <div class="row">
        <div class="col">
            <div class="card" style="width: 18rem; ">
                <img class="card-img-top" src="@Model.ImageUrl">
                <div class="card-body">
                    <h5 class="card-title text-center">Bác Sĩ:  @Model.FullName</h5>
                    <p>Chuyên môn: @Model.Speciality</p>
                    <p>Chi Phí: <i class="bi bi-currency-euro"></i>@Model.ExaminationPrice</p>
                    <p>Giới Tính: @Model.Gender</p>
                    <p>@nameof(Model.Gender): @Model.Gender</p>
                    <p>Địa chỉ: @Model.Address</p>
                    <p class="lead">
                        <a class="btn btn-primary btn-lg" role="button" asp-controller="Appointments" asp-action="Book" asp-route-physicianId="@Model.Id">Đặt lịch hẹn</a>
                    </p>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card float-right" style="width: 18rem; height: 24rem;">
                @if (Model.AverageRating != 0)
                {
                    <h5 class="card-title align-self-center">Average Rating: @Model.AverageRating</h5>
                }
                <div class="card-body">
                    @if (Model.LastReview != null)
                    {
                    <div class="card-body">
                        <h5 class="text-center">Bài đánh giá mới nhất</h5>
                        <div class="pb-2 text-center">
                            <h4>
                                @for (int i = 0; i < Model.LastReview.Rating; i++)
                                {
                                    <i class="bi bi-star-fill text-warning"></i>
                                }
                            </h4>
                        </div>
                        <p>@Model.LastReview.Comment</p>
                        <p>Written On: @Model.LastReview.CreatedOn.ToString("d")</p>
                        <p class="lead">
                            <a class="btn btn-primary btn-lg" role="button" asp-controller="Reviews" asp-action="All" asp-route-physicianId="@Model.Id">Kiểm tra tất cả bài đánh giá</a>
                        </p>
                    </div>
                    }
                    else
                    {
                        <div class="card-body">
                            <p class="text-center">@Model.FullName chưa được xem xét.</p>
                            <h3 class="text-center"><i class="bi bi-star text-warning"></i></h3>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

MedicReach-main/MedicReach/Views/Physicians/Edit.cshtml
@model PhysicianFormModel

@{
    ViewData["Title"] = "Chỉnh sửa hồ sơ Bác sĩ";
}

<partial name="_PhysicianFormPartial" model="@Model" />

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

MedicReach-main/MedicReach/Views/Physicians/_PhysicianFormPartial.cshtml
@model PhysicianFormModel

<div class="container">
    <div class="row">
        <div class="offset-lg-2 col-lg-8 col-sm-12">
            <h2 class="heading-margin text-center">@ViewData["Title"]</h2>
            <form method="post">
                <div class="form-group">
                    <label asp-for="MedicalCenterId">Cơ sở</label>
                    <select asp-for="MedicalCenterId" class="form-control">
                        @foreach (var medicalCenter in Model.MedicalCenters)
                        {
                            <option value="@medicalCenter.Id">
                                @medicalCenter.Name, @medicalCenter.Address, @medicalCenter.City, @medicalCenter.Country
                            </option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="JoiningCode">Mã cơ sở</label>
                    <input asp-for="JoiningCode" class="form-control" placeholder="">
                    <span asp-validation-for="JoiningCode" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <a class="btn btn-primary" asp-controller="MedicalCenters" asp-action="Add">Chọn cơ sở</a>
                </div>
                <div class="form-group">
                    <label asp-for="FullName">Họ và tên</label>
                    <input asp-for="FullName" class="form-control" placeholder="John Johnson, Daniel Smith...">
                    <span asp-validation-for="FullName" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PracticePermissionNumber">Số giấy phép hành nghề</label>
                    <input asp-for="PracticePermissionNumber" class="form-control" placeholder="">
                    <span asp-validation-for="PracticePermissionNumber" class="small text-danger"></span>
                </div>
                @if (User.IsAdmin())
                {
            <div class="form-group">
                <label asp-for="IsApproved">Tình trạng</label>
                <select asp-for="IsApproved" class="form-control">
                    <option value="False">Chưa duyệt</option>
                    <option value="True">Đã duyệt</option>
                </select>
            </div>}
                <div class="form-group">
                    <label asp-for="Gender">Giới tính</label>
                    <select asp-for="Gender" class="form-control">
                        <option value="Male">Nam</option>
                        <option value="Female">Nữ</option>
                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="ImageUrl">Hình ảnh</label>
                    <input asp-for="ImageUrl" class="form-control" placeholder="https://example.com">
                    <span asp-validation-for="ImageUrl" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ExaminationPrice">Chi phí $</label>
                    <input asp-for="ExaminationPrice" class="form-control" placeholder="">
                    <span asp-validation-for="ExaminationPrice" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IsWorkingWithChildren">Thú cưng dưới 1 tháng tuổi</label>
                    <select asp-for="IsWorkingWithChildren" class="form-control">
                        <option value="True">Có</option>
                        <option value="False">Không</option>
                    </select>
                </div>
                <div class="form-group">
                    <label asp-for="SpecialityId">Chuyên môn</label>
                    <select asp-for="SpecialityId" class="form-control">
                        @foreach (var speciality in Model.Specialities)
                        {
            <option value="@speciality.Id">@speciality.Name</option>}
                    </select>
                </div>
                <input class="btn btn-primary" type="submit" value="Lưu" />
            </form>
        </div>
    </div>
</div>

MedicReach-main/MedicReach/Views/Physicians/_PhysiciansPartial.cshtml
@model IEnumerable<PhysicianServiceModel>

<div class="row mb-4 float-none">
    @foreach (var physician in Model)
    {
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" style="width: 18rem; height: 18rem;" src="@physician.ImageUrl" alt="Physician image">
                <div class="card-body">
                    <h5 class="card-title">@physician.FullName</h5>
                    <p class="card-text">@physician.Speciality</p>
                    <a class="btn btn-primary" asp-controller="Physicians" asp-action="Details" asp-route-physicianId="@physician.Id">Chi tiết</a>
                    @if (User.IsAdmin())
                    {
                        <a class="btn btn-warning" asp-controller="Physicians" asp-action="Edit" asp-route-physicianId="@physician.Id">Sửa</a>
                    }
                </div>
            </div>
        </div>
    }
</div>