MedicReach-main/MedicReach/Controllers/PhysiciansController.cs
using AutoMapper;
using MedicReach.Infrastructure;
using MedicReach.Models.Physicians;
using MedicReach.Services.MedicalCenters;
using MedicReach.Services.Physicians;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using static MedicReach.WebConstants;
using static MedicReach.Areas.Admin.AdminConstants;

namespace MedicReach.Controllers
{
    public class PhysiciansController : Controller
    {
        private readonly IPhysicianService physicians;
        private readonly IMedicalCenterService medicalCenters;
        private readonly IMapper mapper;
        private readonly SignInManager<IdentityUser> signInManager;

        public PhysiciansController(
            IPhysicianService physicians,
            IMedicalCenterService medicalCenters,
            IMapper mapper,
            SignInManager<IdentityUser> signInManager)
        {
            this.physicians = physicians;
            this.medicalCenters = medicalCenters;
            this.mapper = mapper;
            this.signInManager = signInManager;
        }

        public IActionResult All([FromQuery] AllPhysiciansQueryModel query)
        {
            var queryResult = this.physicians.All(
                query.Speciality,
                query.MedicalCenter,
                query.SearchTerm,
                query.Sorting,
                query.CurrentPage,
                AllPhysiciansQueryModel.PhysiciansPerPage,
                query.Approved);

            var physicianSpecialities = this.physicians.AllSpecialities();
            var medicalCenters = this.physicians.AllMedicalCenters();

            query.MedicalCenters = medicalCenters;
            query.Specialities = physicianSpecialities;
            query.Physicians = queryResult.Physicians;
            query.TotalPhysicians = queryResult.TotalPhysicians;

            return View(query);
        }

        [Authorize]
        public IActionResult Become()
        {
            var userIsPhysicians = this.physicians.IsPhysician(this.User.GetId());

            if (userIsPhysicians)
            {
                return RedirectToAction(nameof(Mine));
            }

            return View(new PhysicianFormModel
            {
                MedicalCenters = this.physicians.GetMedicalCenters(),
                Specialities = this.physicians.GetSpecialities()
            });
        }

        [Authorize]
        [HttpPost]
        public IActionResult Become(PhysicianFormModel physicianModel)
        {
            if (!this.physicians.MedicalCenterExists(physicianModel.MedicalCenterId))
            {
                this.ModelState.AddModelError(nameof(physicianModel.MedicalCenterId), "Cơ sở không tồn tại.");
            }

            if (!this.physicians.SpecialityExists(physicianModel.SpecialityId))
            {
                this.ModelState.AddModelError(nameof(physicianModel.SpecialityId), "Chuyên môn không tồn tại.");
            }

            if (!this.medicalCenters.IsJoiningCodeCorrect(physicianModel.JoiningCode, physicianModel.MedicalCenterId))
            {
                this.ModelState.AddModelError(nameof(physicianModel.JoiningCode), "Joining code is incorrect.");
            }

            if (this.physicians.PracticePermissionNumberExists(physicianModel.PracticePermissionNumber))
            {
                this.ModelState.AddModelError(nameof(physicianModel.PracticePermissionNumber), "Practice permission number already exists.");
            }

            if (!this.ModelState.IsValid)
            {
                physicianModel.MedicalCenters = this.physicians.GetMedicalCenters();
                physicianModel.Specialities = this.physicians.GetSpecialities();

                return View(physicianModel);
            }

            this.physicians.Create(
                physicianModel.FullName,
                physicianModel.Gender,
                physicianModel.ExaminationPrice,
                physicianModel.MedicalCenterId,
                physicianModel.ImageUrl,
                physicianModel.SpecialityId,
                physicianModel.IsWorkingWithChildren,
                physicianModel.PracticePermissionNumber,
                physicianModel.IsApproved,
                this.User.GetId());

            Task.Run(async () =>
                {
                    await this.signInManager.SignOutAsync();
                })
                .GetAwaiter()
                .GetResult();

            this.TempData[GlobalSuccessMessageKey] = BecomePhysicianSuccessMessage;

            return RedirectToAction("Index", "Home");
        }

        [Authorize(Roles = PhysicianRoleName + "," + AdministratorRoleName)]
        public IActionResult Edit(string physicianId)
        {
            var physician = this.physicians.Details(physicianId);

            var physicianForm = this.mapper.Map<PhysicianFormModel>(physician);

            physicianForm.MedicalCenters = this.physicians.GetMedicalCenters();
            physicianForm.Specialities = this.physicians.GetSpecialities();
            physicianForm.JoiningCode = this.medicalCenters.GetJoiningCode(physicianForm.MedicalCenterId);

            return View(physicianForm);
        }

        [Authorize(Roles = PhysicianRoleName + "," + AdministratorRoleName)]
        [HttpPost]
        public IActionResult Edit(string physicianId, PhysicianFormModel physicianModel)
        {
            if (!this.medicalCenters.IsJoiningCodeCorrect(physicianModel.JoiningCode, physicianModel.MedicalCenterId))
            {
                this.ModelState.AddModelError(nameof(physicianModel.JoiningCode), "Joining code is incorrect.");
            }

            if (!physicianModel.PracticePermissionNumber.Equals(this.physicians.GetPracticePermissionByPhysiciandId(physicianId)))
            {
                if (this.physicians.PracticePermissionNumberExists(physicianModel.PracticePermissionNumber))
                {
                    this.ModelState.AddModelError(nameof(physicianModel.PracticePermissionNumber), "Practice permission number already exists.");
                }
            }

            if (!this.ModelState.IsValid)
            {
                physicianModel.MedicalCenters = this.physicians.GetMedicalCenters();
                physicianModel.Specialities = this.physicians.GetSpecialities();

                return View(physicianModel);
            }

            this.physicians.Edit(
                physicianId,
                physicianModel.FullName,
                physicianModel.Gender,
                physicianModel.ExaminationPrice,
                physicianModel.MedicalCenterId,
                physicianModel.ImageUrl,
                physicianModel.SpecialityId,
                physicianModel.IsWorkingWithChildren,
                physicianModel.PracticePermissionNumber,
                physicianModel.IsApproved,
                this.User.GetId());

            this.TempData[GlobalSuccessMessageKey] = this.User.IsAdmin() ? AdminEditPhysicianSuccessMessage : EditPhysicianSuccessMessage;

            return RedirectToAction(nameof(Details), new { physicianId });
        }

        public IActionResult Details(string physicianId)
        {
            var physician = this.physicians.Details(physicianId);

            return View(physician);
        }

        [Authorize(Roles = PhysicianRoleName)]
        public IActionResult Mine()
        {
            var physicianId = this.physicians.GetPhysicianId(this.User.GetId());

            if (string.IsNullOrEmpty(physicianId))
            {
                return RedirectToAction(nameof(Become));
            }

            return RedirectToAction(nameof(Edit), new { physicianId });
        }
    }
}

MedicReach-main/MedicReach/Controllers/TinTucController.cs
using Microsoft.AspNetCore.Mvc;

namespace MedicReach.Controllers
{
    public class TinTucController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MedicReach-main/MedicReach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="data:image/x-icon;base64,AAABAAEAEBAQAAAAAAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAFBT8AEVwoQAcWowAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACARAgAAAAACIAACIAAAACIiACIiAAAAIgIAICIAAAAiAiIgIgAAACICIiAiAAAAAiIiIiAAAAAgIiIiAgAAACMAAAAyAAAAIyAAAjIAAAAiIAACIgAAACIgAAIiAAAAIiAAAyIAAAAAAAAAAAAAAAAAAAAAAADwPwAA4B8AAMAPAACABwAAgAcAAIAHAACABwAAgAcAAIAHAACABwAAgwcAAIMHAACDBwAAgwcAAMePAAD//wAA" rel="icon" type="image/x-icon" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    @this.RenderSection("Styles", required: false)
</head>
<body style="background-color:lightgrey">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><i class="bi bi-thermometer-half text-danger"></i>PetZone</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MedicalCenters" asp-action="All">Cơ Sở</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Physicians" asp-action="All">Bác Sĩ</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TinTuc" asp-action="All">Tin Tức</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @if (TempData.ContainsKey(WebConstants.GlobalSuccessMessageKey))
        {
            <div class="alert alert-success" role="alert">
                @TempData[WebConstants.GlobalSuccessMessageKey]
            </div>
        }
        @if (TempData.ContainsKey(WebConstants.GlobalErrorMessageKey))
        {
            <div class="alert alert-danger" role="alert">
                @TempData[WebConstants.GlobalErrorMessageKey]
            </div>
        }
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer style="background-color:#fff;" class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.UtcNow.Year - PetZone
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>